apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJZV0l0ZEhkcGJqcG5hSEJmYkd3eGFtZGtXRlpsZFhvNVUxbzRWalJGVjBWbVRGQkhjWEZ2VUd0ak1HaFphamxvIg0KICAgIH0NCiAgfQ0KfQ==
type: kubernetes.io/dockerconfigjson
